# Generated by Django 6.0 on 2025-12-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_freelancer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='freelancer',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
