# Generated by Django 6.0 on 2025-12-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_delete_freelancer_delete_profile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
