# Generated by Django 6.0 on 2025-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0006_delete_register_alter_login_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='freelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
